[psql]
    dbname = "dcrextdata"
    host = "localhost"
    user = "postgres"
    pass = "ojima123"
    sslmode = "disable"
    whitelist=["exchange", 
        "exchange_tick",
        "vsp",
        "vsp_tick",
        "pow_data"]